name: Ejecutar bot cada hora

on:
  schedule:
    - cron: "0 * * * *"  # cada 1 hora
  workflow_dispatch:

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Establecer variables de entorno
        run: |
          echo "EMAIL_ORIGEN=${{ secrets.EMAIL_ORIGEN }}" >> $GITHUB_ENV
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $GITHUB_ENV
          echo "EMAILS_DESTINO=${{ secrets.EMAILS_DESTINO }}" >> $GITHUB_ENV

      - name: Ejecutar el bot
        run: python monitor.py
